info:
  name: trainingInfo ลบ
  type: http
  seq: 4

http:
  method: PUT
  url: http://apiserver:8080/admin/training/1/
  body:
    type: json
    data: "{\r

      \    \"action\" : \"deleteTrainingInfo\"\r

      }"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
